/*
 * TODO List
 *
 * OPEN API for Todo List
 *
 * API version: 1.0.0
 * Contact: baihaqiyazid16@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2001 struct {
	Success bool `json:"success,omitempty"`
}
